"use client";

import { jsPDF } from "jspdf";


export interface GDCandidateData {
  userName: string;
  topic: string;
  date: string;
  sessionId: string;
  scores: {
    total: number;
    relevance: number;
    communication: number;
    leadership: number;
    collaboration: number;
    confidence: number;
    criticalThinking: number;
  };
  metrics: {
    speakingTime: number;
    turnCount: number;
    avgTurnLength: number;
    fillerCount: number;
  };
  coaching: {
    strengths: string[];
    weaknesses: string[];
    betterPhrasing: { original: string; suggested: string }[];
    roadmap: string;
  };
  verdict: string;
}

export interface GDRecruiterData {
  topic: string;
  date: string;
  sessionId: string;
  groupMetrics: {
    synergy: number;
    dominanceBalance: number;
    participationEquality: number;
    topicCoherence: number;
  };
  leaderboard: {
    rank: number;
    name: string;
    score: number;
    verdict: string;
  }[];
  overview: string;
}

const addHeader = (doc: jsPDF, title: string) => {
  const pageWidth = doc.internal.pageSize.getWidth();
  doc.setFillColor(15, 23, 42); // Slate 900
  doc.rect(0, 0, pageWidth, 40, "F");
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("InteractAI", 20, 25);
  
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(title, pageWidth - 20, 25, { align: "right" });
};

const addFooter = (doc: jsPDF, pageNum: number) => {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text(`Generated by InteractAI Intelligence Engine | Page ${pageNum}`, pageWidth / 2, pageHeight - 10, { align: "center" });
};

export const generateCandidatePDF = (data: GDCandidateData) => {
  const doc = new jsPDF();
  const margin = 20;
  let y = 55;

  addHeader(doc, "CANDIDATE PERFORMANCE REPORT");

  // Basic Info
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text(data.userName, margin, y);
  y += 10;
  
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 116, 139);
  doc.text(`Topic: ${data.topic}`, margin, y);
  doc.text(`Session ID: ${data.sessionId}`, 200 - margin, y, { align: "right" });
  y += 15;

  // Score Card
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(margin, y, 170, 40, 3, 3, "F");
  
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("OVERALL READINESS SCORE", margin + 10, y + 15);
  
  doc.setFontSize(24);
  doc.setTextColor(37, 99, 235); // Blue 600
  doc.text(`${data.scores.total}/100`, margin + 10, y + 30);
  
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(12);
  doc.text("RECRUITER VERDICT", margin + 100, y + 15);
  
  const verdictColor = data.verdict === "Shortlist" ? [22, 163, 74] : [220, 38, 38];
  doc.setTextColor(verdictColor[0], verdictColor[1], verdictColor[2]);
  doc.text(data.verdict.toUpperCase(), margin + 100, y + 30);
  
  y += 55;

  // Skills Radar Section (Simulated with bars)
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Skill Proficiency Breakdown", margin, y);
  y += 10;

  const skills = [
    { label: "Topic Relevance", score: data.scores.relevance },
    { label: "Communication Clarity", score: data.scores.communication },
    { label: "Leadership Presence", score: data.scores.leadership },
    { label: "Collaborative Depth", score: data.scores.collaboration },
    { label: "Critical Thinking", score: data.scores.criticalThinking },
    { label: "Confidence", score: data.scores.confidence }
  ];

  skills.forEach(skill => {
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(15, 23, 42);
    doc.text(skill.label, margin, y);
    doc.text(`${skill.score}%`, 190 - margin, y, { align: "right" });
    
    doc.setFillColor(226, 232, 240);
    doc.rect(margin, y + 2, 170, 2, "F");
    doc.setFillColor(37, 99, 235);
    doc.rect(margin, y + 2, 170 * (skill.score / 100), 2, "F");
    y += 12;
  });

  y += 10;

  // Coaching
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(15, 23, 42);
  doc.text("Personalized Coaching & Growth", margin, y);
  y += 10;

  doc.setFontSize(10);
  doc.setTextColor(22, 163, 74);
  doc.text("STRENGTHS", margin, y);
  y += 6;
  doc.setTextColor(15, 23, 42);
  doc.setFont("helvetica", "normal");
  data.coaching.strengths.forEach(s => {
    doc.text(`• ${s}`, margin + 5, y);
    y += 6;
  });

  y += 4;
  doc.setFont("helvetica", "bold");
  doc.setTextColor(220, 38, 38);
  doc.text("AREAS FOR REFINEMENT", margin, y);
  y += 6;
  doc.setTextColor(15, 23, 42);
  doc.setFont("helvetica", "normal");
  data.coaching.weaknesses.forEach(w => {
    doc.text(`• ${w}`, margin + 5, y);
    y += 6;
  });

  y += 10;
  doc.setFont("helvetica", "bold");
  doc.setTextColor(37, 99, 235);
  doc.text("BETTER PHRASING SUGGESTIONS", margin, y);
  y += 8;
  data.coaching.betterPhrasing.forEach(p => {
    doc.setFont("helvetica", "italic");
    doc.setTextColor(100, 116, 139);
    doc.text(`Original: "${p.original}"`, margin + 5, y);
    y += 5;
    doc.setFont("helvetica", "bold");
    doc.setTextColor(15, 23, 42);
    doc.text(`Better: "${p.suggested}"`, margin + 5, y);
    y += 8;
  });

  addFooter(doc, 1);
  doc.save(`${data.userName}_Performance_Report.pdf`);
};

export const generateRecruiterPDF = (data: GDRecruiterData) => {
  const doc = new jsPDF();
  const margin = 20;
  let y = 55;

  addHeader(doc, "RECRUITER EXECUTIVE SUMMARY");

  // Session Overview
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text(`Topic: ${data.topic}`, margin, y);
  y += 10;
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`Date: ${data.date} | Session ID: ${data.sessionId}`, margin, y);
  y += 15;

  // Group Metrics
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Group Intelligence Metrics", margin, y);
  y += 10;

  const gMetrics = [
    { label: "Group Synergy", val: data.groupMetrics.synergy },
    { label: "Dominance Balance", val: data.groupMetrics.dominanceBalance },
    { label: "Participation Equality", val: data.groupMetrics.participationEquality },
    { label: "Topic Coherence", val: data.groupMetrics.topicCoherence }
  ];

  gMetrics.forEach((m, i) => {
    const col = i % 2;
    const row = Math.floor(i / 2);
    const xPos = margin + (col * 85);
    const yPos = y + (row * 20);
    
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(xPos, yPos, 80, 15, 2, 2, "F");
    doc.setFontSize(9);
    doc.setTextColor(100, 116, 139);
    doc.text(m.label, xPos + 5, yPos + 10);
    doc.setFontSize(12);
    doc.setTextColor(37, 99, 235);
    doc.text(`${m.val}%`, xPos + 65, yPos + 10);
  });
  
  y += 50;

  // Overview text
  doc.setFontSize(12);
  doc.setTextColor(15, 23, 42);
  doc.setFont("helvetica", "bold");
  doc.text("Executive Overview", margin, y);
  y += 8;
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  const splitOverview = doc.splitTextToSize(data.overview, 170);
  doc.text(splitOverview, margin, y);
  y += (splitOverview.length * 5) + 15;

  // Leaderboard
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Candidate Leaderboard", margin, y);
  y += 10;

  // Table Header
  doc.setFillColor(15, 23, 42);
  doc.rect(margin, y, 170, 8, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(9);
  doc.text("RANK", margin + 5, y + 5);
  doc.text("CANDIDATE NAME", margin + 25, y + 5);
  doc.text("SCORE", margin + 110, y + 5);
  doc.text("VERDICT", margin + 140, y + 5);
  y += 8;

  data.leaderboard.forEach((c, i) => {
    if (i % 2 === 0) doc.setFillColor(248, 250, 252);
    else doc.setFillColor(255, 255, 255);
    doc.rect(margin, y, 170, 10, "F");
    
    doc.setTextColor(15, 23, 42);
    doc.text(`#${c.rank}`, margin + 5, y + 7);
    doc.text(c.name, margin + 25, y + 7);
    doc.text(`${c.score}`, margin + 110, y + 7);
    
    const vColor = c.verdict === "Shortlist" ? [22, 163, 74] : (c.verdict === "Hold" ? [202, 138, 4] : [220, 38, 38]);
    doc.setTextColor(vColor[0], vColor[1], vColor[2]);
    doc.text(c.verdict, margin + 140, y + 7);
    y += 10;
  });

  addFooter(doc, 1);
  doc.save(`Recruiter_Summary_${data.topic.replace(/\s+/g, '_')}.pdf`);
};
